package com.hf.hfhs.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hf.hfhs.bean.Cucumber;

import com.hf.hfhs.greendao.CucumberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cucumberDaoConfig;

    private final CucumberDao cucumberDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cucumberDaoConfig = daoConfigMap.get(CucumberDao.class).clone();
        cucumberDaoConfig.initIdentityScope(type);

        cucumberDao = new CucumberDao(cucumberDaoConfig, this);

        registerDao(Cucumber.class, cucumberDao);
    }
    
    public void clear() {
        cucumberDaoConfig.clearIdentityScope();
    }

    public CucumberDao getCucumberDao() {
        return cucumberDao;
    }

}
